version: '3'
services:
  voting-app:
    image: your-docker-repo/voting-app:latest
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=your_database_url
      - OTHER_ENV_VARIABLE=other_value
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
