# values-canary.yaml
nameOverride: "voting-app-canary"
fullnameOverride: "voting-app-canary"

service:
  type: LoadBalancer

ingress:
  enabled: true
  hosts:
    - host: your-canary-voting-app-domain.com
      paths:
        - /

canary:
  enabled: true
  replicaCount: 1
  image:
    repository: your-canary-voting-app-image
    tag: latest
  weight: 50
  service:
    name: voting-app-canary
    port: 80
  ingress:
    hosts:
      - host: your-canary-voting-app-domain.com
        paths:
          - /
