---
- name: Provision Docker Image
  hosts: localhost
  become: true  # Pour permettre l'exécution de tâches avec des privilèges élevés (sudo)

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - python3
        - python3-pip

    - name: Install Docker Python library
      pip:
        name: docker

    - name: Your Ansible tasks here
      # Ajoutez vos tâches spécifiques ici
