name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_canary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: platforms/dev/Dockerfile

    - name: Build Docker image
      run: docker build -t your-docker-repo/voting-app:${{ github.sha }} .

    - name: Push Docker image
      run: docker push your-docker-repo/voting-app:${{ github.sha }}

    - name: Deploy Canary Release
      run: |
        helm upgrade --install voting-app ./voting-app \
          -f ./voting-app/values-canary.yaml \
          --set canary.enabled=true \
          --set canary.weight=50
