name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.7.0'  # Mettez à jour la version selon vos besoins

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}/voting-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_REPO }}/voting-app:${{ github.sha }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install voting-app ./Helm/voting-app -f ./Helm/voting-app/values-canary.yaml --set canary.enabled=true --set canary.weight=50